project:
  type: website

website:
  title: "My Explorations With LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/angelicahu10/
      - icon: linkedin
        href: https://www.linkedin.com/in/angelica-hu/
format:
  html:
    theme: cerulean
    css: styles.css

execute:
  freeze: auto


